### ISSUE TITLE
ajax.php

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_coursebank#1]
As a plugin guardian I saw this come through in the plugins db for approval - Great!!!

This looks strange to me:
https://github.com/catalyst/moodle-tool_coursebank/blob/master/ajax.php#L27

usually we use MOODLE_INTERNAL like this:
defined('MOODLE_INTERNAL') || die();

but that obviously isn't what you want here. You might just want to remove the line as I don't think it will actually do anything (unless I'm missing something)

I'm also suspicious to see that the $action allows speedtest and conncheck to occur even if the user isn't logged in. It would probably be good to add some comments to the file to state why Anon access is required.

**Comment by danmarsden** [comment]
this looks strange too:
https://github.com/catalyst/moodle-tool_coursebank/blob/master/index.php#L33

- called after config.php is included.. usually we use the MOODLE_INTERNAL check in files that MUST be included by other files - (classes etc) - files that do not include config.php/

might be worth checking to see if other uses of MOODLE_INTERNAL are correct and add it to classes/include files etc.

**Comment by danmarsden** [comment]
another one: 
https://github.com/catalyst/moodle-tool_coursebank/blob/master/report.php#L32

**Comment by timpricecatalyst** [comment]
I've pushed an update to address this. Have deleted the line from ajax.php, as it wasn;t doing anything, and have moved the check to before the includes in all other files. See:
https://github.com/catalyst/moodle-tool_coursebank/commit/40ab5606cb8330e76c4ff041facb16c4b8844311

**Comment by danmarsden** [comment]
much better thanks!
