### ISSUE TITLE
globals called when already in global scope

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_coursebank#2]
https://github.com/catalyst/moodle-tool_coursebank/blob/master/index.php#L41

you should just be able to remove that line

**Comment by timpricecatalyst** [comment]
Line has been removed. https://github.com/catalyst/moodle-tool_coursebank/commit/8640e860549bae82965f5cfb1811284505165a13

**Comment by danmarsden** [comment]
cool
