### ISSUE TITLE
tool_coursebank_rrmdir()

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_coursebank#3]
function tool_coursebank_rrmdir() makes a call to an undefined function coursebank_rrmdir()

You might find the whole function can be replaced by the moodlelib function remove_dir()

**Comment by timpricecatalyst** [comment]
I've updated the function name to be correct. The idea is that this function calls itself recursively, to delete directories thorughout the tree. See: https://github.com/catalyst/moodle-tool_coursebank/commit/c7e649dfd4c62696d6ef9912d3d9f758565c3bcc

**Comment by danmarsden** [comment]
I'm pretty sure the core Moodle function does that too. I wouldn't expect this to block approval in the plugins directory though.
