### ISSUE TITLE
tool_coursebank_set_config  tool_coursebank_get_config

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_coursebank#4]
the functions:
tool_coursebank_get_config()
tool_coursebank_set_config()

appear to provide a wrapper around the get/set_config functions - I couldn't see the functions used anywhere or a reason why a wrapper is needed around the core functions?

**Comment by danmarsden** [comment]
- I can see the functions - just not sure why core get/set functions aren't used.

**Comment by timpricecatalyst** [comment]
Not really sure what the initial thinking behind this was. Have removed the wrapper functions and used the core functions instead. See: https://github.com/catalyst/moodle-tool_coursebank/commit/99753ef41317aeefad3d04eaa954b387d6ee7a97

**Comment by danmarsden** [comment]
Great! - I hate wrappers that don't actually do anything :-) I just removed a bunch from the attendance plugin code and still have a few more to get rid of.
