### ISSUE TITLE
tool_coursebank_set_cron_lock uses core config instead of config_plugins

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_coursebank#5]
the function tool_coursebank_set_cron_lock() should really be using the config_plugins tables and probably could use set/get_config instead of a wrapper?

**Comment by danmarsden** [comment]
it appears that set_cron_lock uses direct db calls to insert to db (which won't regen cache) and the check to see if lock is set uses core get_config (which will check cache) so I'm not sure if the lock will actually work in production?

**Comment by danmarsden** [comment]
nope - my eyes are deceiving me.. both are hitting the db so it should still work - If the aim of the wrappers is to bypass the cache a good reason for this should probably be clear in the function definitions

**Comment by mudrd8mz** [comment]
Just wondering if the plugin could make use of https://docs.moodle.org/dev/Lock_API

**Comment by timpricecatalyst** [comment]
Due to the desire of supporting Moodle versions 2.4, 2.5 and 2.6 the Lock API was not used, (it was added in 2.7). It was much simpler when writing to keep it consistent across all versions, rather than having to maintain 2 different versions of the same plugin code base.

**Comment by timpricecatalyst** [comment]
There was seemingly no reason we were not using the core get/set config functions, as such I have updated it to use them. See: https://github.com/catalyst/moodle-tool_coursebank/commit/42a7f8fa292885de9220e7deee91deb3a06618f6

**Comment by danmarsden** [comment]
cool - you should also pass the plugin name to the get/set_config vars to store in the config_plugins table instead of the site-level config table. - this also helps with clean-up if the plugin is un-installed

**Comment by danmarsden** [comment]
it would be good to add support for the newer cron stuff at some point in future - will give the admin more control and visibility of the cron process for the coursebank - typically plugin developers will do this sort of thing by providing multiple branches of their code rather than try to build in support for multiple versions in a single release. But I don't expect this would block approval in the plugins db.

**Comment by timpricecatalyst** [comment]
I've added the plugin name to the calls, so that they use the config plugins table. See: https://github.com/catalyst/moodle-tool_coursebank/commit/dfc2d00278f7b485897e92acb6b15997abcdd412

**Comment by danmarsden** [comment]
cool - looks better thanks!
