### ISSUE TITLE
too many parameters in function call

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_coursebank#6]
https://github.com/catalyst/moodle-tool_coursebank/blob/master/locallib.php#L654

https://github.com/catalyst/moodle-tool_coursebank/blob/master/locallib.php#L1640

**Comment by danmarsden** [comment]
another one:
https://github.com/catalyst/moodle-tool_coursebank/blob/master/locallib.php#L1361
https://github.com/catalyst/moodle-tool_coursebank/blob/master/locallib.php#L923

**Comment by timpricecatalyst** [comment]
I've removed the extra params. See: https://github.com/catalyst/moodle-tool_coursebank/commit/eb1ef3e4be9fb7ce05e309648b4852f1a437c8ee

**Comment by danmarsden** [comment]
looks good to me (you can auto-close these in github by including the text "fixes" and then the github issue number which is #6 in this case)
