### ISSUE TITLE
Unsupported syntax in language files

### ISSUE THREAD

**Issue by mudrd8mz** [catalyst/moodle-tool_coursebank#7]
Please see https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

As the concatenation operator is used at the moment, AMOS is unable to parse your language file. Please avoid using it a simply put all the strings into `$string['key'] = 'value';`

**Comment by germanvaleroelizondo** [comment]
AMOS can not translate this plugin :(  Just as explained by David Mudrak above.

The plugin maintainer might also want to have a look at https://docs.moodle.org/dev/Translating_plugins#Non-translatable_strings

**Comment by timpricecatalyst** [comment]
https://github.com/catalyst/moodle-tool_coursebank/commit/b6a8417ec7fc6bd234c829d803204dd09dccd509 fixes #7
