### ISSUE TITLE
parent does not exist - debugging message

### ISSUE THREAD

**Issue by mudrd8mz** [catalyst/moodle-tool_coursebank#8]
Ooops, I missed this during the plugin approval review. When logged in as a student, I am seeing a lot of debugging messages thrown:

    parent does not exist!
    line 914 of /lib/adminlib.php: call to debugging()
    line 58 of /admin/tool/coursebank/settings.php: call to admin_category->add()
    line 76 of /lib/classes/plugininfo/tool.php: call to include()
    line 460 of /admin/settings/plugins.php: call to core\plugininfo\tool->load_settings()
    line 6874 of /lib/adminlib.php: call to require()
    line 3630 of /lib/navigationlib.php: call to admin_get_root()
    line 3491 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()
    line 719 of /lib/pagelib.php: call to settings_navigation->initialise()
    line 768 of /lib/pagelib.php: call to moodle_page->magic_get_settingsnav()
    line 135 of /blocks/settings/block_settings.php: call to moodle_page->__get()
    line 288 of /blocks/moodleblock.class.php: call to block_settings->get_content()
    line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
    line 973 of /lib/blocklib.php: call to block_base->get_content_for_output()
    line 1025 of /lib/blocklib.php: call to block_manager->create_block_contents()
    line 473 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
    line 52 of /theme/clean/layout/columns3.php: call to core_renderer->standard_head_html()
    line 1015 of /lib/outputrenderers.php: call to include()
    line 945 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 164 of /my/index.php: call to core_renderer->header()

The reasons are quite obvious.

BTW, for Moodle versions > 2015051100, are you sure you are not loading the jQuery twice?

**Comment by mudrd8mz** [comment]
D'oh, somewhat related is this

    Can not add jQuery plugins after starting page output!

    line 487 of /lib/outputrequirementslib.php: call to debugging()
    line 431 of /lib/outputrequirementslib.php: call to page_requirements_manager->jquery_plugin()
    line 37 of /admin/tool/coursebank/settings.php: call to page_requirements_manager->jquery()
    line 76 of /lib/classes/plugininfo/tool.php: call to include()
    line 460 of /admin/settings/plugins.php: call to core\plugininfo\tool->load_settings()
    line 6874 of /lib/adminlib.php: call to require()
    line 468 of /lib/classes/plugininfo/base.php: call to admin_get_root()
    line 1294 of /admin/renderer.php: call to core\plugininfo\base->get_settings_url()
    line 372 of /admin/renderer.php: call to core_admin_renderer->plugins_control_panel()
    line 207 of /admin/plugins.php: call to core_admin_renderer->plugin_management_page()

**Comment by timpricecatalyst** [comment]
mudrd8mz I seem to be unable to reproduce that first error. Can you please provide the version you used, any customised permissions to the student role and the page you were on to get that debug message?

**Comment by timpricecatalyst** [comment]
I've also attempted to reproduce the jQuery error in a Moodle 2.9.1+ (20150820), but have not been able to see it. Could you please let us know which version and what page you generated the debug output from?

**Comment by mudrd8mz** [comment]
I don't have the plugin installed any more but IIRC it was recent 2.9.1+, with standard student role setup. The pages I was looking at are apparent from the backtrace pasted above.

The first issue here is clear, you are adding to the admin tree nodes like 'backup' but these nodes do not exist for the student role. Also the second issue is simple to be tracked down from the provided backtrace.

**Comment by timpricecatalyst** [comment]
I've fixed the first issue here: https://github.com/catalyst/moodle-tool_coursebank/commit/61df0e0727017a611deeba5a3021fb7570165ed4

I'm still unable to reproduce the jquery error, I know it's generated on the course bank plugin settings page, but I'm just not getting it to appear in any version I've tried. From what I've read about the error, we may need to convert the settings page to be an admin_externalpage.

**Comment by danmarsden** [comment]
Hi Tim, 

I can reproduce the errors on the Moodle master branch by using the "login as" feature to login as a student.

eg - log in with admin account, press the "login as" link on a student account and the "You are logged in as xxx" page that shows after using the login as option shows the errors.

Your latest patch fixes the "parent does not exist" error but the "Can not add jQuery plugins after starting page output!" error remains.

**Comment by danmarsden** [comment]
this is how the Turnitin plugin sorts this:
https://github.com/jmcgettrick/MoodleDirectV2/blob/master/mod/turnitintooltwo/settings.php#L46

I'm not convinced that is the "right" way and it looks pretty hacky to me.. but it might work-around the issue.

**Comment by timpricecatalyst** [comment]
Thanks for the steps to reproduce, and the suggestion Dan. I have adopted the same hacky fix that Turnitin uses to fix this. See https://github.com/catalyst/moodle-tool_coursebank/commit/e3939efcbf57a3bdf9c8ad8f99ec5aaed84f272c
